[versions]
agp = "8.7.3"
kotlin = "2.0.21"
compose-compiler = "2.0.21"
compose-bom = "2024.12.01"
activity-compose = "1.10.0"
lifecycle = "2.8.7"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }
